permissions:
  contents: write
  pull-requests: write 
  issues: read

name: mlops-classification
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          pip install -r requirements.txt
          dvc repro
          
          git fetch --prune
          
          dvc metrics diff --show-md main > report.md
      
          echo "## Model ROC Plot" >> report.md
          echo "![](./ROC.png)" >> report.md
          
          cml comment create report.md
          
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
